# Generated by Django 4.2.1 on 2023-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mission',
            field=models.CharField(max_length=75),
        ),
    ]
