# Generated by Django 4.2.1 on 2023-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_about_alter_profile_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
