# Generated by Django 4.2.1 on 2023-07-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
