# Generated by Django 4.2.1 on 2023-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
