# Generated by Django 4.2.1 on 2023-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_description_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.FileField(upload_to='markdown/resume/'),
        ),
    ]
