# Generated by Django 4.2.1 on 2023-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.FileField(default=1, upload_to='markdown/projects/'),
            preserve_default=False,
        ),
    ]
