# Generated by Django 4.2.1 on 2023-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(max_length=4096),
        ),
    ]
