# Generated by Django 4.2.1 on 2023-07-05 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_project_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
